import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-gray-50 text-gray-900">
        {/*
          THESIS: A classic SaaS canvas editor (Webflow/Excalidraw finish bar) offering familiar, seamless layout tools without steep learning curves.
          OWN-WORLD: Clean neutral interface, #f3f4f6 grey panels, #ffffff canvas, #2563eb primary buttons, soft dropshadows and 1px borders.
          STORY: The user lands ready to design; tools are exactly where expected, properties appear contextually, and nothing gets in the way of the canvas.
          FIRST VIEWPORT: Top header for save/auth, left tool rail, massive center stage for the canvas, right sidebar for contextual element properties.
          FORM: canon (category standard); seed e35c7703.
          FINISH: unreviewed and undocumented is unfinished; this build ends with the finish review, the verdict, DESIGN.md, and every shipping raster carrying its provenance.
        */}
        {children}
      </body>
    </html>
  );
}
